/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface JobListing {
    id: string;
    applyUrl: string;
    deadline: string;
    department: string;
    position: Position;
    location: string;
    institute: string;
}
export enum Position {
    professor = "professor",
    assistantProfessor = "assistantProfessor",
    associateProfessor = "associateProfessor"
}
export interface backendInterface {
    addJob(institute: string, position: Position, department: string, location: string, deadline: string, applyUrl: string): Promise<string>;
    editJob(id: string, institute: string, position: Position, department: string, location: string, deadline: string, applyUrl: string): Promise<void>;
    filterJobsByDepartment(department: string): Promise<Array<JobListing>>;
    filterJobsByInstitute(institute: string): Promise<Array<JobListing>>;
    filterJobsByLocation(location: string): Promise<Array<JobListing>>;
    filterJobsByPosition(position: Position): Promise<Array<JobListing>>;
    getAllJobs(): Promise<Array<JobListing>>;
    init(): Promise<void>;
    removeJob(id: string): Promise<void>;
    searchJobs(searchTerm: string): Promise<Array<JobListing>>;
}
import type { JobListing as _JobListing, Position as _Position } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addJob(arg0: string, arg1: Position, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, to_candid_Position_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, to_candid_Position_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async editJob(arg0: string, arg1: string, arg2: Position, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editJob(arg0, arg1, to_candid_Position_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editJob(arg0, arg1, to_candid_Position_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async filterJobsByDepartment(arg0: string): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterJobsByDepartment(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterJobsByDepartment(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterJobsByInstitute(arg0: string): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterJobsByInstitute(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterJobsByInstitute(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterJobsByLocation(arg0: string): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterJobsByLocation(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterJobsByLocation(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterJobsByPosition(arg0: Position): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterJobsByPosition(to_candid_Position_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterJobsByPosition(to_candid_Position_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobs(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async removeJob(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeJob(arg0);
            return result;
        }
    }
    async searchJobs(arg0: string): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_JobListing_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobListing): JobListing {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    applyUrl: string;
    deadline: string;
    department: string;
    position: _Position;
    location: string;
    institute: string;
}): {
    id: string;
    applyUrl: string;
    deadline: string;
    department: string;
    position: Position;
    location: string;
    institute: string;
} {
    return {
        id: value.id,
        applyUrl: value.applyUrl,
        deadline: value.deadline,
        department: value.department,
        position: from_candid_Position_n6(_uploadFile, _downloadFile, value.position),
        location: value.location,
        institute: value.institute
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professor: null;
} | {
    assistantProfessor: null;
} | {
    associateProfessor: null;
}): Position {
    return "professor" in value ? Position.professor : "assistantProfessor" in value ? Position.assistantProfessor : "associateProfessor" in value ? Position.associateProfessor : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobListing>): Array<JobListing> {
    return value.map((x)=>from_candid_JobListing_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Position_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): {
    professor: null;
} | {
    assistantProfessor: null;
} | {
    associateProfessor: null;
} {
    return value == Position.professor ? {
        professor: null
    } : value == Position.assistantProfessor ? {
        assistantProfessor: null
    } : value == Position.associateProfessor ? {
        associateProfessor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
