/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface JobListing {
  'id' : string,
  'applyUrl' : string,
  'deadline' : string,
  'department' : string,
  'position' : Position,
  'location' : string,
  'institute' : string,
}
export type Position = { 'professor' : null } |
  { 'assistantProfessor' : null } |
  { 'associateProfessor' : null };
export interface _SERVICE {
  'addJob' : ActorMethod<
    [string, Position, string, string, string, string],
    string
  >,
  'editJob' : ActorMethod<
    [string, string, Position, string, string, string, string],
    undefined
  >,
  'filterJobsByDepartment' : ActorMethod<[string], Array<JobListing>>,
  'filterJobsByInstitute' : ActorMethod<[string], Array<JobListing>>,
  'filterJobsByLocation' : ActorMethod<[string], Array<JobListing>>,
  'filterJobsByPosition' : ActorMethod<[Position], Array<JobListing>>,
  'getAllJobs' : ActorMethod<[], Array<JobListing>>,
  'init' : ActorMethod<[], undefined>,
  'removeJob' : ActorMethod<[string], undefined>,
  'searchJobs' : ActorMethod<[string], Array<JobListing>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];