/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Position = IDL.Variant({
  'professor' : IDL.Null,
  'assistantProfessor' : IDL.Null,
  'associateProfessor' : IDL.Null,
});
export const JobListing = IDL.Record({
  'id' : IDL.Text,
  'applyUrl' : IDL.Text,
  'deadline' : IDL.Text,
  'department' : IDL.Text,
  'position' : Position,
  'location' : IDL.Text,
  'institute' : IDL.Text,
});

export const idlService = IDL.Service({
  'addJob' : IDL.Func(
      [IDL.Text, Position, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'editJob' : IDL.Func(
      [IDL.Text, IDL.Text, Position, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'filterJobsByDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'filterJobsByInstitute' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'filterJobsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'filterJobsByPosition' : IDL.Func(
      [Position],
      [IDL.Vec(JobListing)],
      ['query'],
    ),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'init' : IDL.Func([], [], []),
  'removeJob' : IDL.Func([IDL.Text], [], []),
  'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Position = IDL.Variant({
    'professor' : IDL.Null,
    'assistantProfessor' : IDL.Null,
    'associateProfessor' : IDL.Null,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Text,
    'applyUrl' : IDL.Text,
    'deadline' : IDL.Text,
    'department' : IDL.Text,
    'position' : Position,
    'location' : IDL.Text,
    'institute' : IDL.Text,
  });
  
  return IDL.Service({
    'addJob' : IDL.Func(
        [IDL.Text, Position, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'editJob' : IDL.Func(
        [IDL.Text, IDL.Text, Position, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'filterJobsByDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'filterJobsByInstitute' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'filterJobsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'filterJobsByPosition' : IDL.Func(
        [Position],
        [IDL.Vec(JobListing)],
        ['query'],
      ),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'init' : IDL.Func([], [], []),
    'removeJob' : IDL.Func([IDL.Text], [], []),
    'searchJobs' : IDL.Func([IDL.Text], [IDL.Vec(JobListing)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };